// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBeTN2TBXsMwBGgtQYvPUNfPdBipY-7lU',
    appId: '1:184006771200:web:ca72324156e896c4b70ee5',
    messagingSenderId: '184006771200',
    projectId: 'freelance-connect-app',
    authDomain: 'freelance-connect-app.firebaseapp.com',
    storageBucket: 'freelance-connect-app.appspot.com',
    measurementId: 'G-PHVKWJG1WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjfUhmjUnhcZWj4BNRpHZRgnx8x8xBTPs',
    appId: '1:184006771200:android:5756dd94f4781401b70ee5',
    messagingSenderId: '184006771200',
    projectId: 'freelance-connect-app',
    storageBucket: 'freelance-connect-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNlVyJu2CMbv1XISaLNyXII681dY7jMI',
    appId: '1:184006771200:ios:63a116d76ebc3aebb70ee5',
    messagingSenderId: '184006771200',
    projectId: 'freelance-connect-app',
    storageBucket: 'freelance-connect-app.appspot.com',
    iosBundleId: 'com.example.campusFreelanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNlVyJu2CMbv1XISaLNyXII681dY7jMI',
    appId: '1:184006771200:ios:63a116d76ebc3aebb70ee5',
    messagingSenderId: '184006771200',
    projectId: 'freelance-connect-app',
    storageBucket: 'freelance-connect-app.appspot.com',
    iosBundleId: 'com.example.campusFreelanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBeTN2TBXsMwBGgtQYvPUNfPdBipY-7lU',
    appId: '1:184006771200:web:cd2ddaf125df69d6b70ee5',
    messagingSenderId: '184006771200',
    projectId: 'freelance-connect-app',
    authDomain: 'freelance-connect-app.firebaseapp.com',
    storageBucket: 'freelance-connect-app.appspot.com',
    measurementId: 'G-TFX4QM1GCE',
  );

}